apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: capstone-uma-deployment
spec:
  selector:
    matchLabels:
      app: capstone-uma
  replicas: 3 
  template:
    metadata:
      labels:
        app: capstone-uma
    spec:
      containers:
      - name: capstone-uma-container 
        image: umamages/devops_project
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: capstone-uma-service
spec:
  type: NodePort
  selector:
    app: capstone-uma
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32100      
